### ISSUE TITLE
Peers seem to be incorrect 

### ISSUE THREAD

**Issue by Dranaxel** [y-polek/TransmissionRemote#114]
Hi,

I sometimes need to edit the trackers of my download and here is what I find `http://preferedwebsite.org:8080` instead of the full adress : 
`http://preferredw ebsite.org:8080/S12591KWT3HFVPdADX08A1oy20l5276R/announce`
The problems appears on all the torrents.

I'm using the app on a one plus 5T with android 10

**Comment by simba83** [comment]
I think more information is needed and i actually don't think this is app related.
My guess is that you use a DNS name for your home IP and use a portforward from you router to your transmission server.
When you are on the local network things work one way and when outside your network things work differently since your portforward is only used from WAN and not LAN.

**Comment by Dranaxel** [comment]
Hi,

I don't use any port forwarding or DNS on my local network. After seeing this issue I installed tremotesref which Is working and same with transmission on desktop (Windows) so I would be surprised the problem doesn't come from the application...
